# 开发环境配置
server:
  # 服务端口
  port: 1240

spring:
  rabbitmq:
    host: 127.0.0.1
    username: admin
    password: admin
    port: 5672
    virtual-host: /
    listener:
      simple:
        concurrency: 10 # Minimum number of consumers.
        max-concurrency: 30 # Maximum number of consumers.
        prefetch: 10
        retry:
          enabled: true #是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
          max-attempts: 3 #重试次数
          initial-interval: 5000ms
        acknowledge-mode: manual        #消费方手动ack
      direct:
        acknowledge-mode: manual        #消费方手动ack
    publisher-returns: true             #发送方的return与confirm模式保证信息发出成功
    publisher-confirms: true

